---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver_config:
      box: ubuntu/xenial64
      network:
        - ['private_network', {ip: '172.16.33.33'}]
    run_list:
      - recipe[lxd_cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
        {
        register_on_sauron: 'false'
        }
  - name: lxd_cluster
    driver_config:
      box: ubuntu/xenial64
      hostname: lxd-cluster-01
      network:
        - ['private_network', {ip: '172.16.33.33'}]
    run_list:
      - recipe[lxd_cookbook::lxd_cluster]
    verifier:
      inspec_tests:
        - test/smoke/lxd_cluster
